#!/bin/bash

source $FREERTOS_PROJ_ROOT/env/control-pulp-fpga.sh

export PCF_TARGET=PMS_CV32
export PCF_PLATFORM=FPGA_ZCU102

cd $PCF_PATH

if [[ $1 = "blocking" ]]
then
    make clean RISCV="/usr/pack/riscv-1.0-kgf/pulp-gcc-2.5.0-rc1" CFLAGS="-Og -g3 -march=rv32imac_zfinx_xcorev -mabi=ilp32 -DFEATURE_CLUSTER=1 -D__PULP__=1 -DDEBUG" ASFLAGS="-Os -g3 -march=rv32imac_zfinx_xcorev -mabi=ilp32" \
    			MAKE_FLAGS="-UUSE_FIXED_VOLTAGE -UUSE_MONTE_CIMONE \
    			-DMEMORY_FIXED_FETCH -DUSE_INSTRUCTIONS_COMPOSITION -DPRINTF_ACTIVE -DPCF_USE_CLUSTER -UPCF_USE_CLUSTER_PARALL \
    			-DTASKS_PERIOD_MULTIPLIER=200 -DPCF_FREERTOS_TICK_RATE_HZ=5 -DDEFAULT_SYSTEM_CLOCK=20000000u \
    			-UCI_TEST -DCI_TEST_ITERATION=100 -UMEASURE_ACTIVE \
    			" all 

elif [[ $1 = "async" ]]
then
    make clean RISCV="/usr/pack/riscv-1.0-kgf/pulp-gcc-2.5.0-rc1" CFLAGS="-Og -g3 -march=rv32imac_zfinx_xcorev -mabi=ilp32 -DFEATURE_CLUSTER=1 -D__PULP__=1 -DDEBUG" ASFLAGS="-Os -g3 -march=rv32imac_zfinx_xcorev -mabi=ilp32" \
    			MAKE_FLAGS="-UUSE_FIXED_VOLTAGE -UUSE_MONTE_CIMONE \
    			-DMEMORY_FIXED_FETCH -DUSE_INSTRUCTIONS_COMPOSITION -DPRINTF_ACTIVE -DPCF_USE_CLUSTER -DPCF_USE_CLUSTER_PARALL \
    			-DTASKS_PERIOD_MULTIPLIER=200 -DPCF_FREERTOS_TICK_RATE_HZ=5 -DDEFAULT_SYSTEM_CLOCK=20000000u \
    			-UCI_TEST -DCI_TEST_ITERATION=100 -UMEASURE_ACTIVE \
    			" all 
else
	
	#make clean RISCV="/opt/riscv" CFLAGS="-Og -g3 -march=rv32imac_zfinx_xcorev -mabi=ilp32 -DFEATURE_CLUSTER=1 -D__PULP__=1 -DDEBUG" ASFLAGS="-Os -g3 -march=rv32imac_zfinx_xcorev -mabi=ilp32" \
	make clean RISCV="/usr/pack/riscv-1.0-kgf/pulp-gcc-2.5.0-rc1" CFLAGS="-Og -g3 -march=rv32imac_zfinx_xcorev -mabi=ilp32 -DFEATURE_CLUSTER=1 -D__PULP__=1 -DDEBUG" ASFLAGS="-Os -g3 -march=rv32imac_zfinx_xcorev -mabi=ilp32" \
				MAKE_FLAGS="-UUSE_FIXED_VOLTAGE -DUSE_MONTE_CIMONE \
				-DMEMORY_FIXED_FETCH -DUSE_INSTRUCTIONS_COMPOSITION -DPRINTF_ACTIVE -UPCF_USE_CLUSTER -UPCF_USE_CLUSTER_PARALL \
				-DTASKS_PERIOD_MULTIPLIER=200 -DPCF_FREERTOS_TICK_RATE_HZ=5 -DDEFAULT_SYSTEM_CLOCK=20000000u \
				-UCI_TEST -DCI_TEST_ITERATION=100 -UMEASURE_ACTIVE \
				" all 

	#CI TEST, with PRINTF
	#make clean RISCV="/usr/pack/riscv-1.0-kgf/pulp-gcc-2.5.0-rc1" CFLAGS="-Og -g3 -march=rv32imc_zfinx_xcorev -mabi=ilp32" ASFLAGS="-Os -g3 -march=rv32imc_zfinx_xcorev -mabi=ilp32" MAKE_FLAGS="-DMEMORY_FIXED_FETCH -DUSE_INSTRUCTIONS_COMPOSITION -DTASKS_PERIOD_MULTIPLIER=5 -DCI_TEST -DCI_TEST_ITERATION=1000 -UMEASURE_ACTIVE -DPRINTF_ACTIVE -DPCF_FREERTOS_TICK_RATE_HZ=250 -DDEFAULT_SYSTEM_CLOCK=20000000u" all

	#Cycles print
	#make clean RISCV="/usr/pack/riscv-1.0-kgf/pulp-gcc-2.5.0-rc1" CFLAGS="-Og -g3 -march=rv32imc_zfinx_xcorev -mabi=ilp32" ASFLAGS="-Os -g3 -march=rv32imc_zfinx_xcorev -mabi=ilp32" MAKE_FLAGS="-DMEMORY_FIXED_FETCH -DUSE_INSTRUCTIONS_COMPOSITION -DTASKS_PERIOD_MULTIPLIER=10 -UCI_TEST -DMEASURE_ACTIVE=1 -DMEASURE_N_ITERATION=20 -DMEASURE_N_OUTPUTS=64 -DPRINTF_ACTIVE -DPCF_FREERTOS_TICK_RATE_HZ=125 -DDEFAULT_SYSTEM_CLOCK=20000000u" all
fi


cd


